### ISSUE TITLE
Enable simple startup configuration file selection/history

### ISSUE THREAD

**Issue by gselzer** [gselzer/pymmcore-plus-sandbox#10]
Currently, we load in the (shipped) demo configuration on startup. Ideally we would conveniently remember some number of configurations. Below are the questions we must answer to complete this:

**What happens on first startup?**
* Launch the UI without a configuration
* Launch the UI with the demo configuration (do we ship it, or download it from somewhere?)
* Prompt the user via QDialog (or CLI argument) for a path to a configuration file

**Should we try to remember previous config selections?**
* Allow the user to automatically load config from a defined path (perhaps set in a configuration window)
* Load the last used configuration file, or prompt the user for a path using QDialog like Micromanager does

**How should we retain user configuration preferences?**
* [`configparser`](https://docs.python.org/3/library/configparser.html)
* [`confuse`](https://pypi.org/project/confuse/), which is used by e.g. napari-imagej.
* something else (there are many other options)

@marktsuchida unless you have preferences, I tentatively will choose:
* No configuration on first startup
* Develop a configuration window, which will be used to define a configuration file to be loaded on startup (and could later expose other configuration options)
* `configparser` to retain user data

**Comment by marktsuchida** [comment]
I think those choices sound good until we have reason to use something else. Correctly displaying (with unavailable functions disabled) when no config is loaded seems like a good thing.

(BTW You don't need to download or find the demo config, because pymmcore-plus will automatically find it if you call `loadSystemConfiguration` without an argument.)
