### ISSUE TITLE
Show the property browser

### ISSUE THREAD

**Issue by marktsuchida** [gselzer/pymmcore-plus-sandbox#4]
For playing with this on the microscope, it will probably be hard without at least this. For now it can be just a button that opens the pymmcore-widgets PropertyBrowser.

Something to study for the longer term is how to coordinate things like the PropertyBrowser with Live and MDA. This simplest is to disallow all property setting while either is going on. For the Live case, we could be nicer (e.g., disallow setting all but the active cameras' properties, or handling camera property changes specially by stopping and restarting the Live acquisition). For the MDA case, too, we could allow changes but they need to occur at specific stages in the MDA engine (unless it can be proven that the property is not affected by the particular MDA being run). These ideas may require extensions to the widgets and/or engine as well.

**Comment by gselzer** [comment]
The `PropertyBrowser` widget has been added with 3c2c41014dafe0957a8f3736b88c82fa73ef5b60

@marktsuchida would you like to narrow this issue to the longer-term nuances you describe with Live/MDA, or would you like those to belong within separate issues?

**Comment by marktsuchida** [comment]
Thanks, I extracted that into a separate issue (which can be further split as necessary).
